"LR": 0.004
"NUM_ENVS": 128
"NUM_STEPS": 128
"GRU_HIDDEN_DIM": 128
"FC_DIM_SIZE": 128
"TOTAL_TIMESTEPS": 1e8
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.05
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.25
"ACTIVATION": "relu"
"ENV_NAME": "HeuristicEnemySMAX"
"MAP_NAME": "4m_vs_6m"
"SEED": 0
"ENV_KWARGS": 
  "see_enemy_actions": True
  "walls_cause_death": True
  "attack_mode": "closest"
"ANNEAL_LR": True

# WandB Params
"ENTITY": "syan"
"PROJECT": "jax"
"WANDB_MODE" : "online" #"disabled" #

# GAGE params
"GAGE_TOPK_INIT": 1.4
"OPTIM_GOAL": 1.0
"GAGE_ETA1": 2.0
"GAGE_ETA2": 1.0 # keep value 1.0